spring:
  application:
    name: affable-bean-backend

  datasource:
    url: jdbc:mysql://localhost:3306/newdb
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8090